#
# $Id$
#

- name: install and configure zabbix frontend packages
  block:
    - apk:
        name:
          - lighttpd
          - fcgi
          - php7-common
          - php7-iconv
          - php7-json
          - php7-gd
          - php7-curl
          - php7-xml
          - php7-mysqli
          - php7-imap
          - php7-cgi
          - php7-pdo
          - php7-pdo_mysql
          - php7-soap
          - php7-xmlrpc
          - php7-posix
          - php7-mcrypt
          - php7-gettext
          - php7-ldap
          - php7-ctype
          - php7-dom
          - zabbix-webif
    - template: src=lighttpd.conf.j2 dest=/etc/lighttpd/lighttpd.conf
    - template: src=mod_fastcgi.conf.j2 dest=/etc/lighttpd/mod_fastcgi.conf
    - template: src=php.ini.j2 dest=/etc/php7/php.ini
    - template: src=zabbix.conf.php.j2 dest=/usr/share/webapps/zabbix/conf/zabbix.conf.php
    - service: name=lighttpd state=restarted
  when: force_reinstall|bool is true
